import AppKit
import XCTest
#if canImport(TopkitCore)
@testable import TopkitCore
#elseif canImport(Topkit)
@testable import Topkit
#endif

final class ClipboardPasteboardHelpersTests: XCTestCase {
    private func makePasteboard() -> NSPasteboard {
        let pb = NSPasteboard(name: NSPasteboard.Name("topkit.test.\(UUID().uuidString)"))
        pb.clearContents()
        return pb
    }

    func testPlainTextDoesNotSkip() {
        let pb = makePasteboard()
        pb.setString("hello", forType: .string)
        XCTAssertFalse(ClipboardPasteboardHelpers.shouldSkipPasteboardDueToSensitiveType(pb))
    }

    func testConcealedTypeSkips() {
        let pb = makePasteboard()
        pb.setData(Data(), forType: ClipboardPasteboardHelpers.concealedPasteboardType)
        pb.setString("secret", forType: .string)
        XCTAssertTrue(ClipboardPasteboardHelpers.shouldSkipPasteboardDueToSensitiveType(pb))
    }

    func testTransientTypeSkips() {
        let pb = makePasteboard()
        pb.setData(Data(), forType: ClipboardPasteboardHelpers.transientPasteboardType)
        pb.setString("ephemeral", forType: .string)
        XCTAssertTrue(ClipboardPasteboardHelpers.shouldSkipPasteboardDueToSensitiveType(pb))
    }

    func testAutoGeneratedTypeSkips() {
        let pb = makePasteboard()
        pb.setData(Data(), forType: ClipboardPasteboardHelpers.autoGeneratedPasteboardType)
        pb.setString("programmatic", forType: .string)
        XCTAssertTrue(ClipboardPasteboardHelpers.shouldSkipPasteboardDueToSensitiveType(pb))
    }
}
