import AppKit
import Foundation

enum ClipboardPasteboardHelpers {
    /// Matches `org.nspasteboard.ConcealedType` (e.g. 1Password, Bitwarden).
    static let concealedPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// Matches `org.nspasteboard.TransientType` — ephemeral writes (paste helpers, format
    /// converters) that clipboard managers are expected to ignore.
    static let transientPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// Matches `org.nspasteboard.AutoGeneratedType` — programmatic writes not initiated by the user.
    static let autoGeneratedPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private static let skippedTypes: [NSPasteboard.PasteboardType] = [
        concealedPasteboardType,
        transientPasteboardType,
        autoGeneratedPasteboardType
    ]

    /// When the pasteboard advertises a concealed, transient, or auto-generated marker
    /// (nspasteboard.org conventions), clipboard history must not record contents.
    static func shouldSkipPasteboardDueToSensitiveType(_ pasteboard: NSPasteboard) -> Bool {
        pasteboard.availableType(from: skippedTypes) != nil
    }
}
